Repository Cajeh/aula_git, pull requests merged in 2019-09, with the labels that each got.

#8 Base para classe Banco criada
  Banco.java
Labels: enhancement

#7 Base para a classe Cliente criada
  Cliente.java
Labels: enhancement

#6 Atualizar .gitignore
  .gitignore
Labels: documentation

#13 Cajeh#1
  Conta.java
Labels: enhancement

#17 Joao#4
  operacoes.java
Labels: enhancement

#22 Refatorar classe menu para mandar opções para o banco
  Menu.java
  Operacoes.java
Labels: bug

#24 joao#21
  Banco.java
Labels: bug
